name: overview

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: 'ngi'
      - run: nix build .#overview
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'result'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Use GH_PAT for authentication
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "Using GitHub Token..."
          # Example: git push or API calls using $GH_PAT
      - id: deployment
        uses: actions/deploy-pages@v4
