on:
  push:
    branches:
    - main
    - feature/*
    - bugfix/*
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
     - name: install haxe
       run: cd $GITHUB_WORKSPACE
     - name: install haxe
       run: set && ls -la && ./make install
     - name: transpile haxe into languages
       run: ./make
     - name: run tests
       run: ./make runtest
