on:
  push:
    branches:
    - main
    - feature/*
    - bugfix/*

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
     - name: install haxe
       run: ls -la && ./make install
     - name: transpile haxe into languages
       run: ./make
     - name: run tests
       run: ./make runtest
