on:
  push:
    branches:
    - main
    - feature/*
    - bugfix/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - name: install haxe
       run: set && ls -la && ./make install
     - name: transpile haxe into languages
       run: ./make
     - name: run tests
       run: ./make runtest
