name: test

on:
  push:
    branches:
    - main
    - feature/*
    - bugfix/*
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: install haxe
        run: ./make install
      - name: transpile haxe into languages
        run: ./make
      - name: run tests
        run: ./make tests
