name: update

on:
  workflow_dispatch:
  schedule:
    - cron: '17 1 * * Mon'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v12

      - uses: DeterminateSystems/update-flake-lock@v23
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          pr-title: "flake: Update flake.lock"
          pr-labels: |
            automated
